### PR TITLE
Adding new example file 

### PR DESCRIPTION
**Pull request by ShazAlvi**
Hi Priase,

I hope that I have done everything right, as per your instructions. Let me know if I need to do anything.

### CODE REVIEW

**Comment by prisae** [comment]
Looks good, thanks. I'll have a look at it probably at the weekend. Thanks!

**Comment by ShazAlvi** [comment]
Sure, thing. Thank you!

**Comment by prisae** [comment]
Hi @ShazAlvi ,

I had a look today, and I think many issues that you encountered are because the transform pair you try to resolve is not smooth in both domains. The sine is smooth in the time domain, but it the frequency domain it is an impulse response, so inherently not smooth. In this way, FFTLog will probably never work very stable, and you have to do lots of try-and-error. It is probably also why the automatic `kr`-finding doesn't work.

I think that if we want to include the example we should change it to a transform-pair which is smooth in both, frequency and time domain (e.g., a Gaussian or similar). But we can also keep it with this example to show that it is possible to get it to work even in this case. Up to you. However, we should make a note then of the issue.

Anyhow, if you are willing to iterate over it I would like to ask you for some changes (I could make them, but it is better you do and get attribution for it then).

Please:
- Rename the file from `fftlog_FourierSineTransform_Example.py` to `sinetransform.py` (or `sinecosinetransform.py` or something similar, just all lowercase, without `fftlog` or `example` in it).
- Change the title from `FFTLog-Test` to `Sine Transform` (or `Sine/Cosine Transform` or something appropriate).
- Remove all the text from the FFTLog-Test-example, as this should be an example on its own.
- It should follow pep8-standards (https://www.python.org/dev/peps/pep-0008/) - what I require is that `flake8` runs without errors. You can install it via `pip install flake8`, and then run `flake8 examples/sinetransform.py` to test it. We can work through this together, if there are any issues.

Anyhow, just if you have the time. Let me know how you get on!

**Comment by prisae** [comment]
Ah, also, at the moment there is a mixture of `x`, `k`, `r`, etc. As it is a Fourier transform it would probably be best to just use `t` and `f` for time- and frequency-domain, respectively.

**Comment by ShazAlvi** [comment]
Hi @prisae ,

Thanks for your feedback and the explanation. Yes, what you are explaining sounds about right. I intended to do a transform of a simple sine wave because its Fourier transform would be simple and I know what to expect in the a(k) distribution. I will work on the file as you suggest and get back to you about it, perhaps sometimes this week.

Thanks again!

**Comment by ShazAlvi** [comment]
Hi @prisae Sorry for being absent. I had incorporated most of the suggestions in to the file but I could not get to understand how to do the flake8 thing. I installed flake8 but I do not know how to work with it. I use MS VSCode for most of my coding and it has some version of Flake8 built-it, as far as I have learned. That is the only thing left. How do you suggest we work with Flake8? 

Sorry, again, for being absent.

**Comment by prisae** [comment]
No problem at all, there is no hurry.

Do you work on windows?

On Mac/Linux you would run flake8 in the terminal, e.g.,
```
flake8 yourfile.py
```
not sure how it works on Windows. If you use conda then you could do it just the same. There might be VSCode plugins doing that, see e.g., https://stackoverflow.com/questions/54160207/using-flake8-in-vscode.

If you don't get it running now worries, just commit it like this for now.

**Comment by ShazAlvi** [comment]
Yes, I use windows. Let me try to run that command on Windows console and see how it goes.  Thanks for the link, I will check that out.

**Comment by ShazAlvi** [comment]
All changes, done. Flake8 gives zero problems in formatting. Thanks for telling me about Flake8 (Y).  I have "Commit" all the changes.

**Comment by prisae** [comment]
Hi ShazAlvi! Thanks for that. There are a few bits to change, and I think I want to have it in a user-provided example folders. But I do that once it is merged. Thanks for the example! I hope `pyfftlog` will be useful for you!

**Comment by prisae** [comment]
Hi @ShazAlvi, here you go:
https://pyfftlog.readthedocs.io/en/latest/examples/contrib/sinetransform.html

I re-structured the examples a bit, added your name, and did some other little things. I hope it is OK, otherwise let me know!

**Comment by ShazAlvi** [comment]
Hi @prisae , Thanks. It looks perfect. I made some small corrections (symbolism related, I was still using k and r in some places instead of f and t) in the comments and proposed the changes.  Thanks, again. (Y).

**Comment by prisae** [comment]
Hi @ShazAlvi -> where did you make the comments? (I can't see them, but I am happy to include any further edits on it.)

**Comment by ShazAlvi** [comment]
I can't see them either now. Sorry, I am new to GitHub. I made changes in the comments like these, 

Line 31: # logtmax = 0.798 #2\pi,
Line 114: # the distribution of the a(t) vs t.
Line 68: # Central point log10(t_c) of periodic interval

And, similar things (these are the ones I can remember at the moment).

**Comment by prisae** [comment]
It is all about learning ;-)

If you go here:
https://github.com/prisae/pyfftlog/blob/master/examples/contrib/sinetransform.py
and then hit the pencil-symbol
Selection_001
you can directly edit it in the GitHub interface.

At the end you can commit it (it will automatically create a fork for you and subsequently a PR, as you don't have the necessary rights on prisae/pyfftlog).

Selection_002

**Comment by ShazAlvi** [comment]
Thanks. When I tried last time, I did the same in your directory. At the end it gave me the option called, "Propose Changes" instead of Commit changes. I thought it would generate a proposal for you to approve or something. Let me try your method and see how it goes. Thank for being patient with me :)

**Comment by prisae** [comment]
Yes, it will say 'Propose Changes' in your case, but then it should create a fork automatically with a PR...

**Pull request merged**
